//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 06:26:03 AM CET 
//


package pl.moj.xmlschemat;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for cena complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cena">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://moj.pl/xmlschemat>wartośćCeny">
 *       &lt;attribute name="waluta" type="{http://moj.pl/xmlschemat}waluta" default="złotych" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cena", propOrder = {
    "value"
})
public class Cena {

    @XmlValue
    protected BigDecimal value;
    @XmlAttribute(name = "waluta")
    protected Waluta waluta;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the waluta property.
     * 
     * @return
     *     possible object is
     *     {@link Waluta }
     *     
     */
    public Waluta getWaluta() {
        if (waluta == null) {
            return Waluta.ZŁOTYCH;
        } else {
            return waluta;
        }
    }

    /**
     * Sets the value of the waluta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Waluta }
     *     
     */
    public void setWaluta(Waluta value) {
        this.waluta = value;
    }

}
