//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 06:26:03 AM CET 
//


package pl.moj.xmlschemat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for dataZałożenia complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dataZałożenia">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dzień" type="{http://moj.pl/xmlschemat}dzień"/>
 *         &lt;element name="miesiąc" type="{http://moj.pl/xmlschemat}miesiąc"/>
 *         &lt;element name="rok" type="{http://moj.pl/xmlschemat}rok"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dataZałożenia", propOrder = {
    "dzień",
    "miesiąc",
    "rok"
})
public class DataZałożenia {

    @XmlSchemaType(name = "positiveInteger")
    protected int dzień;
    @XmlSchemaType(name = "positiveInteger")
    protected int miesiąc;
    @XmlSchemaType(name = "positiveInteger")
    protected int rok;

    /**
     * Gets the value of the dzień property.
     * 
     */
    public int getDzień() {
        return dzień;
    }

    /**
     * Sets the value of the dzień property.
     * 
     */
    public void setDzień(int value) {
        this.dzień = value;
    }

    /**
     * Gets the value of the miesiąc property.
     * 
     */
    public int getMiesiąc() {
        return miesiąc;
    }

    /**
     * Sets the value of the miesiąc property.
     * 
     */
    public void setMiesiąc(int value) {
        this.miesiąc = value;
    }

    /**
     * Gets the value of the rok property.
     * 
     */
    public int getRok() {
        return rok;
    }

    /**
     * Sets the value of the rok property.
     * 
     */
    public void setRok(int value) {
        this.rok = value;
    }

}
