/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.moj.xmlschemat;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import javax.xml.XMLConstants;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;
import org.xml.sax.InputSource;

/**
 *
 * @author Przemyslaw Swiderski, Damian Deska
 */
public class GUI extends javax.swing.JFrame
{

    public static Płytoteka płytoteka;

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        System.out.println("Program do zadania 4.");
        System.out.println("Autorzy:");
        System.out.println("Przemysław Świderski, Damian Deska");

        czytajXML();

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        WykonawcyFrame = new javax.swing.JFrame();
        WykonawcyScrollPanel = new javax.swing.JScrollPane();
        WykonawcyTable = new javax.swing.JTable();
        ZamknijWykonawcowButton = new javax.swing.JButton();
        KasujWykonawceButton = new javax.swing.JButton();
        PłytyFrame = new javax.swing.JFrame();
        PłytyScrollPanel = new javax.swing.JScrollPane();
        PłytyTable = new javax.swing.JTable();
        ZamknijPłtytButton = new javax.swing.JButton();
        KasujPłyteButton = new javax.swing.JButton();
        WydawcyFrame = new javax.swing.JFrame();
        WydawcyScrollPanel = new javax.swing.JScrollPane();
        WydawcyTable = new javax.swing.JTable();
        ZamknijWydawcowButton = new javax.swing.JButton();
        KasujWydawceButton = new javax.swing.JButton();
        CzytajDialog = new javax.swing.JDialog();
        ZamknijCzytajButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ZapiszDialog = new javax.swing.JDialog();
        SuccesLabel = new javax.swing.JLabel();
        ZamknijCzytajButton1 = new javax.swing.JButton();
        ErrorLabel = new javax.swing.JLabel();
        DodajWykonawceFrame = new javax.swing.JFrame();
        DodajButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ImieTextField = new javax.swing.JTextField();
        NazwiskoTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ZamknijDodajWykButton = new javax.swing.JButton();
        DodajWydawceFrame = new javax.swing.JFrame();
        DodajNowegoWydawceButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        PaństwoTxt = new javax.swing.JTextField();
        NazwaTxt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ZamknijDodajWydButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DniWydawcaFormTxt = new javax.swing.JTextField();
        MiesiacWydawcaFromTxt = new javax.swing.JTextField();
        rokWydawcaFormText = new javax.swing.JTextField();
        AdresWydawcaFormTxt = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        TelefonWydawcaFormTxt = new javax.swing.JTextField();
        DodajPłyteFrame = new javax.swing.JFrame();
        DodajButton3 = new javax.swing.JButton();
        ZamknijDodajWykButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CzyPolskaCheckBox = new javax.swing.JCheckBox();
        InniWykonawcyTxt = new javax.swing.JTextField();
        TytułTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ArtystaTxt = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        CenaTxt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        WalutaComboBox = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        DniWydaniaTxt = new javax.swing.JTextField();
        MiesiacWydaniaTxt = new javax.swing.JTextField();
        RokWydaniaTxt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        LiczbaSztukTxt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        WydawcaComboBox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        GatunekComboBox = new javax.swing.JComboBox();
        InfoFrame = new javax.swing.JFrame();
        ZamknijInfoButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OpisTextArea = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AutorzyTextArea = new javax.swing.JTextArea();
        Płyty = new javax.swing.JButton();
        Wydawcy = new javax.swing.JButton();
        Wykonawcy = new javax.swing.JButton();
        ZamknijButton = new javax.swing.JButton();
        CzytajXMLButton = new javax.swing.JButton();
        ZapiszXMLButton = new javax.swing.JButton();
        DodajPłyteButton = new javax.swing.JButton();
        DodajWydawceButton = new javax.swing.JButton();
        DodajWykonawceButton = new javax.swing.JButton();
        GoToInfoButton = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        WykonawcyFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WykonawcyFrame.setTitle("Wykonawcy");
        WykonawcyFrame.setMinimumSize(new java.awt.Dimension(450, 350));

        WykonawcyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        WykonawcyScrollPanel.setViewportView(WykonawcyTable);

        ZamknijWykonawcowButton.setText("Zamknij");
        ZamknijWykonawcowButton.addActionListener(formListener);

        KasujWykonawceButton.setText("Kasuj");
        KasujWykonawceButton.addActionListener(formListener);

        javax.swing.GroupLayout WykonawcyFrameLayout = new javax.swing.GroupLayout(WykonawcyFrame.getContentPane());
        WykonawcyFrame.getContentPane().setLayout(WykonawcyFrameLayout);
        WykonawcyFrameLayout.setHorizontalGroup(
            WykonawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WykonawcyFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WykonawcyScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(WykonawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ZamknijWykonawcowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(KasujWykonawceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        WykonawcyFrameLayout.setVerticalGroup(
            WykonawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WykonawcyFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WykonawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WykonawcyFrameLayout.createSequentialGroup()
                        .addComponent(KasujWykonawceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(ZamknijWykonawcowButton))
                    .addComponent(WykonawcyScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        PłytyFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PłytyFrame.setTitle("Płyty");
        PłytyFrame.setMinimumSize(new java.awt.Dimension(750, 600));

        PłytyScrollPanel.setMinimumSize(new java.awt.Dimension(420, 420));

        PłytyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PłytyTable.setMinimumSize(new java.awt.Dimension(220, 220));
        PłytyScrollPanel.setViewportView(PłytyTable);

        ZamknijPłtytButton.setText("Zamknij");
        ZamknijPłtytButton.addActionListener(formListener);

        KasujPłyteButton.setText("Kasuj");
        KasujPłyteButton.addActionListener(formListener);

        javax.swing.GroupLayout PłytyFrameLayout = new javax.swing.GroupLayout(PłytyFrame.getContentPane());
        PłytyFrame.getContentPane().setLayout(PłytyFrameLayout);
        PłytyFrameLayout.setHorizontalGroup(
            PłytyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PłytyFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PłytyScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PłytyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KasujPłyteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ZamknijPłtytButton, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                .addContainerGap())
        );
        PłytyFrameLayout.setVerticalGroup(
            PłytyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PłytyFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PłytyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PłytyScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 328, Short.MAX_VALUE)
                    .addGroup(PłytyFrameLayout.createSequentialGroup()
                        .addComponent(KasujPłyteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ZamknijPłtytButton)
                        .addGap(39, 39, 39))))
        );

        WydawcyFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        WydawcyFrame.setTitle("Wydawcy");
        WydawcyFrame.setMinimumSize(new java.awt.Dimension(700, 600));

        WydawcyScrollPanel.setMinimumSize(new java.awt.Dimension(220, 220));

        WydawcyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        WydawcyTable.setMaximumSize(new java.awt.Dimension(2147483647, 23164));
        WydawcyTable.setMinimumSize(new java.awt.Dimension(200, 264));
        WydawcyScrollPanel.setViewportView(WydawcyTable);

        ZamknijWydawcowButton.setText("Zamknij");
        ZamknijWydawcowButton.addActionListener(formListener);

        KasujWydawceButton.setText("Kasuj");
        KasujWydawceButton.addActionListener(formListener);

        javax.swing.GroupLayout WydawcyFrameLayout = new javax.swing.GroupLayout(WydawcyFrame.getContentPane());
        WydawcyFrame.getContentPane().setLayout(WydawcyFrameLayout);
        WydawcyFrameLayout.setHorizontalGroup(
            WydawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WydawcyFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(WydawcyScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(WydawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KasujWydawceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ZamknijWydawcowButton, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                .addContainerGap())
        );
        WydawcyFrameLayout.setVerticalGroup(
            WydawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WydawcyFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(WydawcyFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(WydawcyFrameLayout.createSequentialGroup()
                        .addComponent(KasujWydawceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 214, Short.MAX_VALUE)
                        .addComponent(ZamknijWydawcowButton))
                    .addComponent(WydawcyScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        CzytajDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        CzytajDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        ZamknijCzytajButton.setText("Zamknij");
        ZamknijCzytajButton.addActionListener(formListener);

        jLabel1.setText("Pomyślnie Wszytano obiekty do Programu");

        javax.swing.GroupLayout CzytajDialogLayout = new javax.swing.GroupLayout(CzytajDialog.getContentPane());
        CzytajDialog.getContentPane().setLayout(CzytajDialogLayout);
        CzytajDialogLayout.setHorizontalGroup(
            CzytajDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CzytajDialogLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(CzytajDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CzytajDialogLayout.createSequentialGroup()
                        .addComponent(ZamknijCzytajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CzytajDialogLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))))
        );
        CzytajDialogLayout.setVerticalGroup(
            CzytajDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CzytajDialogLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ZamknijCzytajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        ZapiszDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        SuccesLabel.setText("Pomyślnie Zapisano Plik do xml_out.xml.");

        ZamknijCzytajButton1.setText("Zamknij");
        ZamknijCzytajButton1.addActionListener(formListener);

        ErrorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ErrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        ErrorLabel.setText("Błąd w zapisie i walidacji z xsd.");

        javax.swing.GroupLayout ZapiszDialogLayout = new javax.swing.GroupLayout(ZapiszDialog.getContentPane());
        ZapiszDialog.getContentPane().setLayout(ZapiszDialogLayout);
        ZapiszDialogLayout.setHorizontalGroup(
            ZapiszDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapiszDialogLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(ZapiszDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ZapiszDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapiszDialogLayout.createSequentialGroup()
                            .addComponent(ZamknijCzytajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(123, 123, 123))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapiszDialogLayout.createSequentialGroup()
                            .addComponent(SuccesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)))))
        );
        ZapiszDialogLayout.setVerticalGroup(
            ZapiszDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZapiszDialogLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(ErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SuccesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ZamknijCzytajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        DodajWykonawceFrame.setMinimumSize(new java.awt.Dimension(430, 300));

        DodajButton.setText("DODAJ");
        DodajButton.addActionListener(formListener);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Imie");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Nazwisko");

        ZamknijDodajWykButton.setText("Zamknij");
        ZamknijDodajWykButton.addActionListener(formListener);

        javax.swing.GroupLayout DodajWykonawceFrameLayout = new javax.swing.GroupLayout(DodajWykonawceFrame.getContentPane());
        DodajWykonawceFrame.getContentPane().setLayout(DodajWykonawceFrameLayout);
        DodajWykonawceFrameLayout.setHorizontalGroup(
            DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DodajWykonawceFrameLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DodajWykonawceFrameLayout.createSequentialGroup()
                        .addComponent(ZamknijDodajWykButton)
                        .addGap(179, 179, 179)
                        .addComponent(DodajButton))
                    .addGroup(DodajWykonawceFrameLayout.createSequentialGroup()
                        .addGroup(DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DodajWykonawceFrameLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(DodajWykonawceFrameLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)))
                        .addGroup(DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ImieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NazwiskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        DodajWykonawceFrameLayout.setVerticalGroup(
            DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DodajWykonawceFrameLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NazwiskoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(DodajWykonawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DodajButton)
                    .addComponent(ZamknijDodajWykButton))
                .addGap(82, 82, 82))
        );

        DodajWydawceFrame.setMinimumSize(new java.awt.Dimension(430, 400));

        DodajNowegoWydawceButton.setText("DODAJ");
        DodajNowegoWydawceButton.addActionListener(formListener);

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setText("Data Założenia");

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setText("Nazwa");

        ZamknijDodajWydButton.setText("Zamknij");
        ZamknijDodajWydButton.addActionListener(formListener);

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("Adres");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setText("Państwo");

        DniWydawcaFormTxt.setText("dd");

        MiesiacWydawcaFromTxt.setText("mm");

        rokWydawcaFormText.setText("rok");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setText("Telefon");

        javax.swing.GroupLayout DodajWydawceFrameLayout = new javax.swing.GroupLayout(DodajWydawceFrame.getContentPane());
        DodajWydawceFrame.getContentPane().setLayout(DodajWydawceFrameLayout);
        DodajWydawceFrameLayout.setHorizontalGroup(
            DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DodajWydawceFrameLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(DodajWydawceFrameLayout.createSequentialGroup()
                            .addComponent(ZamknijDodajWydButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DodajNowegoWydawceButton)
                            .addGap(42, 42, 42))
                        .addGroup(DodajWydawceFrameLayout.createSequentialGroup()
                            .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(NazwaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(DodajWydawceFrameLayout.createSequentialGroup()
                                    .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46)
                                    .addComponent(PaństwoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(61, 61, 61)))
                    .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(DodajWydawceFrameLayout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(62, 62, 62)
                            .addComponent(DniWydawcaFormTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(MiesiacWydawcaFromTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(rokWydawcaFormText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, DodajWydawceFrameLayout.createSequentialGroup()
                            .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TelefonWydawcaFormTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(AdresWydawcaFormTxt))))))
        );
        DodajWydawceFrameLayout.setVerticalGroup(
            DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DodajWydawceFrameLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NazwaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaństwoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DniWydawcaFormTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiesiacWydawcaFromTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rokWydawcaFormText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdresWydawcaFormTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonWydawcaFormTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DodajWydawceFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZamknijDodajWydButton)
                    .addComponent(DodajNowegoWydawceButton))
                .addGap(22, 22, 22))
        );

        DodajPłyteFrame.setMinimumSize(new java.awt.Dimension(700, 600));

        DodajButton3.setText("DODAJ");
        DodajButton3.addActionListener(formListener);

        ZamknijDodajWykButton3.setText("Zamknij");
        ZamknijDodajWykButton3.addActionListener(formListener);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Czy Polska");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Inni Wykonawcy");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Tytuł");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setText("Artysta");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setText("Cena");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TytułTxt)
                            .addComponent(ArtystaTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(CzyPolskaCheckBox))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(InniWykonawcyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(CenaTxt)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CzyPolskaCheckBox)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InniWykonawcyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TytułTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ArtystaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CenaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setText("Data Wydania");

        WalutaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "złotych", "euro", "dolarów" }));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel20.setText("Waluta");

        DniWydaniaTxt.setText("dd");

        MiesiacWydaniaTxt.setText("mm");

        RokWydaniaTxt.setText("rok");

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setText("Gatunek");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setText("Liczba Sztuk");

        WydawcaComboBox.setModel(DataModel.getWydawcyComboBoxModel());
        WydawcaComboBox.addActionListener(formListener);

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setText("Wydawca");

        GatunekComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pop", "Rock", "Country", "Jazz", "Disco", "Inny" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LiczbaSztukTxt))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(WalutaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DniWydaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MiesiacWydaniaTxt)))
                        .addGap(27, 27, 27)
                        .addComponent(RokWydaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WydawcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GatunekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WalutaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DniWydaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MiesiacWydaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RokWydaniaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LiczbaSztukTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WydawcaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GatunekComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout DodajPłyteFrameLayout = new javax.swing.GroupLayout(DodajPłyteFrame.getContentPane());
        DodajPłyteFrame.getContentPane().setLayout(DodajPłyteFrameLayout);
        DodajPłyteFrameLayout.setHorizontalGroup(
            DodajPłyteFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DodajPłyteFrameLayout.createSequentialGroup()
                .addGroup(DodajPłyteFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DodajPłyteFrameLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(ZamknijDodajWykButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DodajButton3))
                    .addGroup(DodajPłyteFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        DodajPłyteFrameLayout.setVerticalGroup(
            DodajPłyteFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DodajPłyteFrameLayout.createSequentialGroup()
                .addGroup(DodajPłyteFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DodajPłyteFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DodajPłyteFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZamknijDodajWykButton3)
                    .addComponent(DodajButton3))
                .addGap(20, 20, 20))
        );

        InfoFrame.setMinimumSize(new java.awt.Dimension(430, 400));

        ZamknijInfoButton.setText("Zamknij");
        ZamknijInfoButton.addActionListener(formListener);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("AUTORZY");

        OpisTextArea.setColumns(20);
        OpisTextArea.setRows(5);
        jScrollPane1.setViewportView(OpisTextArea);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("OPIS");

        AutorzyTextArea.setColumns(20);
        AutorzyTextArea.setRows(5);
        jScrollPane2.setViewportView(AutorzyTextArea);

        javax.swing.GroupLayout InfoFrameLayout = new javax.swing.GroupLayout(InfoFrame.getContentPane());
        InfoFrame.getContentPane().setLayout(InfoFrameLayout);
        InfoFrameLayout.setHorizontalGroup(
            InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoFrameLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(InfoFrameLayout.createSequentialGroup()
                .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoFrameLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ZamknijInfoButton)))
                    .addGroup(InfoFrameLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        InfoFrameLayout.setVerticalGroup(
            InfoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ZamknijInfoButton)
                .addGap(21, 21, 21))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Zadanie 4");
        setMinimumSize(new java.awt.Dimension(430, 300));

        Płyty.setText("Zarządzaj Płytami");
        Płyty.addActionListener(formListener);

        Wydawcy.setText("Zarządzaj Wydawcami");
        Wydawcy.addActionListener(formListener);

        Wykonawcy.setText("Zarządzaj Wykonawcami");
        Wykonawcy.addActionListener(formListener);

        ZamknijButton.setText("Zamknij");
        ZamknijButton.addActionListener(formListener);

        CzytajXMLButton.setText("Czytaj");
        CzytajXMLButton.addActionListener(formListener);

        ZapiszXMLButton.setText("Zapisz");
        ZapiszXMLButton.addActionListener(formListener);

        DodajPłyteButton.setText("Dodaj Płyte");
        DodajPłyteButton.addActionListener(formListener);

        DodajWydawceButton.setText("Dodaj Wydawce");
        DodajWydawceButton.addActionListener(formListener);

        DodajWykonawceButton.setText("Dodaj Wykonawce");
        DodajWykonawceButton.addActionListener(formListener);

        GoToInfoButton.setText("XMLInfo");
        GoToInfoButton.addActionListener(formListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(CzytajXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Wykonawcy, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(Płyty, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Wydawcy, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ZapiszXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajPłyteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DodajWykonawceButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(DodajWydawceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(ZamknijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(GoToInfoButton)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Płyty, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajPłyteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wydawcy, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajWydawceButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Wykonawcy, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DodajWykonawceButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CzytajXMLButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ZapiszXMLButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ZamknijButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GoToInfoButton))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener
    {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt)
        {
            if (evt.getSource() == Płyty)
            {
                GUI.this.PłytyActionPerformed(evt);
            }
            else if (evt.getSource() == Wydawcy)
            {
                GUI.this.WydawcyActionPerformed(evt);
            }
            else if (evt.getSource() == Wykonawcy)
            {
                GUI.this.WykonawcyActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijButton)
            {
                GUI.this.ZamknijButtonActionPerformed(evt);
            }
            else if (evt.getSource() == CzytajXMLButton)
            {
                GUI.this.CzytajXMLButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZapiszXMLButton)
            {
                GUI.this.ZapiszXMLButtonActionPerformed(evt);
            }
            else if (evt.getSource() == DodajPłyteButton)
            {
                GUI.this.DodajPłyteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == DodajWydawceButton)
            {
                GUI.this.DodajWydawceButtonActionPerformed(evt);
            }
            else if (evt.getSource() == DodajWykonawceButton)
            {
                GUI.this.DodajWykonawceButtonActionPerformed(evt);
            }
            else if (evt.getSource() == GoToInfoButton)
            {
                GUI.this.GoToInfoButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijWykonawcowButton)
            {
                GUI.this.ZamknijWykonawcowButtonActionPerformed(evt);
            }
            else if (evt.getSource() == KasujWykonawceButton)
            {
                GUI.this.KasujWykonawceButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijPłtytButton)
            {
                GUI.this.ZamknijPłtytButtonActionPerformed(evt);
            }
            else if (evt.getSource() == KasujPłyteButton)
            {
                GUI.this.KasujPłyteButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijWydawcowButton)
            {
                GUI.this.ZamknijWydawcowButtonActionPerformed(evt);
            }
            else if (evt.getSource() == KasujWydawceButton)
            {
                GUI.this.KasujWydawceButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijCzytajButton)
            {
                GUI.this.ZamknijCzytajButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijCzytajButton1)
            {
                GUI.this.ZamknijCzytajButton1ActionPerformed(evt);
            }
            else if (evt.getSource() == DodajButton)
            {
                GUI.this.DodajButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijDodajWykButton)
            {
                GUI.this.ZamknijDodajWykButtonActionPerformed(evt);
            }
            else if (evt.getSource() == DodajNowegoWydawceButton)
            {
                GUI.this.DodajNowegoWydawceButtonActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijDodajWydButton)
            {
                GUI.this.ZamknijDodajWydButtonActionPerformed(evt);
            }
            else if (evt.getSource() == DodajButton3)
            {
                GUI.this.DodajButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijDodajWykButton3)
            {
                GUI.this.ZamknijDodajWykButton3ActionPerformed(evt);
            }
            else if (evt.getSource() == ZamknijInfoButton)
            {
                GUI.this.ZamknijInfoButtonActionPerformed(evt);
            }
            else if (evt.getSource() == WydawcaComboBox)
            {
                GUI.this.WydawcaComboBoxActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void ZamknijButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijButtonActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ZamknijButtonActionPerformed

    private void ZamknijWykonawcowButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijWykonawcowButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijWykonawcowButtonActionPerformed
        WykonawcyFrame.dispose();
    }//GEN-LAST:event_ZamknijWykonawcowButtonActionPerformed

    private void WykonawcyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_WykonawcyActionPerformed
    {//GEN-HEADEREND:event_WykonawcyActionPerformed
        WykonawcyTable.setModel(DataModel.getWykonawcyTableModel());
        WykonawcyFrame.setVisible(true);
    }//GEN-LAST:event_WykonawcyActionPerformed

    private void KasujWykonawceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_KasujWykonawceButtonActionPerformed
    {//GEN-HEADEREND:event_KasujWykonawceButtonActionPerformed
        try
        {
            płytoteka.wykonawcy.getWykonawca().remove(WykonawcyTable.getSelectedRow());
            WykonawcyTable.setModel(DataModel.getWykonawcyTableModel());
        } catch (IndexOutOfBoundsException e)
        {
        }
    }//GEN-LAST:event_KasujWykonawceButtonActionPerformed

    private void ZamknijPłtytButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijPłtytButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijPłtytButtonActionPerformed
        PłytyFrame.dispose();
    }//GEN-LAST:event_ZamknijPłtytButtonActionPerformed

    private void KasujPłyteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_KasujPłyteButtonActionPerformed
    {//GEN-HEADEREND:event_KasujPłyteButtonActionPerformed
        try
        {
            płytoteka.katalogPłyt.płyta.remove(PłytyTable.getSelectedRow());
            PłytyTable.setModel(DataModel.getPłytyTableModel());
        } catch (IndexOutOfBoundsException e)
        {
        }
    }//GEN-LAST:event_KasujPłyteButtonActionPerformed

    private void ZamknijWydawcowButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijWydawcowButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijWydawcowButtonActionPerformed

        WydawcyFrame.dispose();
    }//GEN-LAST:event_ZamknijWydawcowButtonActionPerformed

    private void KasujWydawceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_KasujWydawceButtonActionPerformed
    {//GEN-HEADEREND:event_KasujWydawceButtonActionPerformed
        try
        {
            płytoteka.wydawcy.getWydawca().remove(WydawcyTable.getSelectedRow());
            WydawcyTable.setModel(DataModel.getWydawcyTableModel());
            WydawcaComboBox.setModel(DataModel.getWydawcyComboBoxModel());
        } catch (IndexOutOfBoundsException e)
        {
        }
    }//GEN-LAST:event_KasujWydawceButtonActionPerformed

    private void WydawcyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_WydawcyActionPerformed
    {//GEN-HEADEREND:event_WydawcyActionPerformed
        WydawcyTable.setModel(DataModel.getWydawcyTableModel());
        WydawcyFrame.setVisible(true);
    }//GEN-LAST:event_WydawcyActionPerformed

    private void PłytyActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_PłytyActionPerformed
    {//GEN-HEADEREND:event_PłytyActionPerformed
        PłytyTable.setModel(DataModel.getPłytyTableModel());
        PłytyFrame.setVisible(true);
    }//GEN-LAST:event_PłytyActionPerformed

    private void CzytajXMLButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_CzytajXMLButtonActionPerformed
    {//GEN-HEADEREND:event_CzytajXMLButtonActionPerformed
        czytajXML();
        CzytajDialog.setVisible(true);
        WydawcaComboBox.setModel(DataModel.getWydawcyComboBoxModel());
    }//GEN-LAST:event_CzytajXMLButtonActionPerformed

    private void ZapiszXMLButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZapiszXMLButtonActionPerformed
    {//GEN-HEADEREND:event_ZapiszXMLButtonActionPerformed
        if (zapiszXMLdoPliku())
        {
            ZapiszDialog.setVisible(true);
            SuccesLabel.setVisible(true);
            ErrorLabel.setVisible(false);
        } else
        {
            ZapiszDialog.setVisible(true);
            SuccesLabel.setVisible(false);
            ErrorLabel.setVisible(true);
        }


    }//GEN-LAST:event_ZapiszXMLButtonActionPerformed

    private void ZamknijCzytajButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijCzytajButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijCzytajButtonActionPerformed
        CzytajDialog.dispose();
    }//GEN-LAST:event_ZamknijCzytajButtonActionPerformed

    private void ZamknijCzytajButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijCzytajButton1ActionPerformed
    {//GEN-HEADEREND:event_ZamknijCzytajButton1ActionPerformed
        ZapiszDialog.dispose();
    }//GEN-LAST:event_ZamknijCzytajButton1ActionPerformed

    private void DodajButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DodajButtonActionPerformed
    {//GEN-HEADEREND:event_DodajButtonActionPerformed
        DataModel.dodajWykonawce(ImieTextField.getText(), NazwiskoTextField.getText());
    }//GEN-LAST:event_DodajButtonActionPerformed

    private void ZamknijDodajWykButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijDodajWykButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijDodajWykButtonActionPerformed
        DodajWykonawceFrame.dispose();
    }//GEN-LAST:event_ZamknijDodajWykButtonActionPerformed

    private void DodajWykonawceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DodajWykonawceButtonActionPerformed
    {//GEN-HEADEREND:event_DodajWykonawceButtonActionPerformed
        DodajWykonawceFrame.setVisible(true);
    }//GEN-LAST:event_DodajWykonawceButtonActionPerformed

    private void DodajNowegoWydawceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DodajNowegoWydawceButtonActionPerformed
    {//GEN-HEADEREND:event_DodajNowegoWydawceButtonActionPerformed
        DataModel.dodajWydawce(NazwaTxt.getText(), PaństwoTxt.getText(), DniWydawcaFormTxt.getText(), MiesiacWydawcaFromTxt.getText(), rokWydawcaFormText.getText(), TelefonWydawcaFormTxt.getText(), AdresWydawcaFormTxt.getText());
    }//GEN-LAST:event_DodajNowegoWydawceButtonActionPerformed

    private void ZamknijDodajWydButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijDodajWydButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijDodajWydButtonActionPerformed
        DodajWydawceFrame.dispose();
    }//GEN-LAST:event_ZamknijDodajWydButtonActionPerformed

    private void DodajButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DodajButton3ActionPerformed
    {//GEN-HEADEREND:event_DodajButton3ActionPerformed
        DataModel.dodajPłyte(CzyPolskaCheckBox.isSelected(), InniWykonawcyTxt.getText(), TytułTxt.getText(), ArtystaTxt.getText(), CenaTxt.getText(),(String) WalutaComboBox.getSelectedItem(), DniWydaniaTxt.getText(), MiesiacWydaniaTxt.getText(), RokWydaniaTxt.getText(), LiczbaSztukTxt.getText(), (String) WydawcaComboBox.getSelectedItem(), (String) GatunekComboBox.getSelectedItem());
    }//GEN-LAST:event_DodajButton3ActionPerformed

    private void ZamknijDodajWykButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijDodajWykButton3ActionPerformed
    {//GEN-HEADEREND:event_ZamknijDodajWykButton3ActionPerformed
        DodajPłyteFrame.dispose();
    }//GEN-LAST:event_ZamknijDodajWykButton3ActionPerformed

    private void DodajWydawceButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DodajWydawceButtonActionPerformed
    {//GEN-HEADEREND:event_DodajWydawceButtonActionPerformed
        DodajWydawceFrame.setVisible(true);
    }//GEN-LAST:event_DodajWydawceButtonActionPerformed

    private void ZamknijInfoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijInfoButtonActionPerformed
    {//GEN-HEADEREND:event_ZamknijInfoButtonActionPerformed
        InfoFrame.dispose();
    }//GEN-LAST:event_ZamknijInfoButtonActionPerformed

    private void GoToInfoButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_GoToInfoButtonActionPerformed
    {//GEN-HEADEREND:event_GoToInfoButtonActionPerformed
        OpisTextArea.setText(płytoteka.info.opis);
        AutorzyTextArea.setText(płytoteka.info.autorzy.autor.get(0).getValue()+" "+płytoteka.info.autorzy.autor.get(1).getValue());
        InfoFrame.setVisible(true);
    }//GEN-LAST:event_GoToInfoButtonActionPerformed

    private void DodajPłyteButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DodajPłyteButtonActionPerformed
    {//GEN-HEADEREND:event_DodajPłyteButtonActionPerformed
        DodajPłyteFrame.setVisible(true);
    }//GEN-LAST:event_DodajPłyteButtonActionPerformed

    private void WydawcaComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_WydawcaComboBoxActionPerformed
    {//GEN-HEADEREND:event_WydawcaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WydawcaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new GUI().setVisible(true);

            }
        });
    }

    public void czytajXML()
    {
        try (InputStreamReader isr = new InputStreamReader(new FileInputStream("src/xml_in.xml"), "UTF-8");)
        {
            SchemaFactory sf = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            Schema schema = sf.newSchema(new File("src/xsd.xsd"));

            JAXBContext ctx = JAXBContext.newInstance("pl.moj.xmlschemat");
            Unmarshaller umrs = ctx.createUnmarshaller();
            umrs.setSchema(schema);
            umrs.setEventHandler(new MyValidationEventHandler());
            JAXBElement readElem = (JAXBElement) umrs.unmarshal(new InputSource(isr));

            płytoteka = (Płytoteka) readElem.getValue();

            System.out.println("Pomyślnie odczytano obiekty z pliku xml.");
        } catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public Boolean zapiszXMLdoPliku()
    {
        try
        {
            SchemaFactory sf = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            Schema schema = sf.newSchema(new File("src/xsd.xsd"));

            JAXBContext ctx = JAXBContext.newInstance("pl.moj.xmlschemat");

            File fileOutput = new File("src/xml_out.xml");
            Marshaller jaxbMarshaller = ctx.createMarshaller();
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            //jaxbMarshaller.marshal(płytoteka, System.out);
            jaxbMarshaller.setSchema(schema);
            MyValidationEventHandler m = new MyValidationEventHandler();
            jaxbMarshaller.setEventHandler(m);
            jaxbMarshaller.marshal(płytoteka, fileOutput);
            if (m.badValidation)
            {
                System.out.println("Błąd walidacji.");
                return false;
            } else
            {
                System.out.println("Pomyślnie zapisano obiekty do pliku xml.");
                return true;
            }
        } catch (Exception e)
        {
            e.printStackTrace();
            return false;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdresWydawcaFormTxt;
    private javax.swing.JTextField ArtystaTxt;
    private javax.swing.JTextArea AutorzyTextArea;
    private javax.swing.JTextField CenaTxt;
    private javax.swing.JCheckBox CzyPolskaCheckBox;
    private javax.swing.JDialog CzytajDialog;
    private javax.swing.JButton CzytajXMLButton;
    private javax.swing.JTextField DniWydaniaTxt;
    private javax.swing.JTextField DniWydawcaFormTxt;
    private javax.swing.JButton DodajButton;
    private javax.swing.JButton DodajButton3;
    private javax.swing.JButton DodajNowegoWydawceButton;
    private javax.swing.JButton DodajPłyteButton;
    private javax.swing.JFrame DodajPłyteFrame;
    private javax.swing.JButton DodajWydawceButton;
    private javax.swing.JFrame DodajWydawceFrame;
    private javax.swing.JButton DodajWykonawceButton;
    private javax.swing.JFrame DodajWykonawceFrame;
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JComboBox GatunekComboBox;
    private javax.swing.JButton GoToInfoButton;
    private javax.swing.JTextField ImieTextField;
    private javax.swing.JFrame InfoFrame;
    private javax.swing.JTextField InniWykonawcyTxt;
    private javax.swing.JButton KasujPłyteButton;
    private javax.swing.JButton KasujWydawceButton;
    private javax.swing.JButton KasujWykonawceButton;
    private javax.swing.JTextField LiczbaSztukTxt;
    private javax.swing.JTextField MiesiacWydaniaTxt;
    private javax.swing.JTextField MiesiacWydawcaFromTxt;
    private javax.swing.JTextField NazwaTxt;
    private javax.swing.JTextField NazwiskoTextField;
    private javax.swing.JTextArea OpisTextArea;
    private javax.swing.JTextField PaństwoTxt;
    private javax.swing.JButton Płyty;
    private javax.swing.JFrame PłytyFrame;
    private javax.swing.JScrollPane PłytyScrollPanel;
    private javax.swing.JTable PłytyTable;
    private javax.swing.JTextField RokWydaniaTxt;
    private javax.swing.JLabel SuccesLabel;
    private javax.swing.JTextField TelefonWydawcaFormTxt;
    private javax.swing.JTextField TytułTxt;
    private javax.swing.JComboBox WalutaComboBox;
    private javax.swing.JComboBox WydawcaComboBox;
    private javax.swing.JButton Wydawcy;
    private javax.swing.JFrame WydawcyFrame;
    private javax.swing.JScrollPane WydawcyScrollPanel;
    private javax.swing.JTable WydawcyTable;
    private javax.swing.JButton Wykonawcy;
    private javax.swing.JFrame WykonawcyFrame;
    private javax.swing.JScrollPane WykonawcyScrollPanel;
    private javax.swing.JTable WykonawcyTable;
    private javax.swing.JButton ZamknijButton;
    private javax.swing.JButton ZamknijCzytajButton;
    private javax.swing.JButton ZamknijCzytajButton1;
    private javax.swing.JButton ZamknijDodajWydButton;
    private javax.swing.JButton ZamknijDodajWykButton;
    private javax.swing.JButton ZamknijDodajWykButton3;
    private javax.swing.JButton ZamknijInfoButton;
    private javax.swing.JButton ZamknijPłtytButton;
    private javax.swing.JButton ZamknijWydawcowButton;
    private javax.swing.JButton ZamknijWykonawcowButton;
    private javax.swing.JDialog ZapiszDialog;
    private javax.swing.JButton ZapiszXMLButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField rokWydawcaFormText;
    // End of variables declaration//GEN-END:variables
}
