//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 06:26:03 AM CET 
//


package pl.moj.xmlschemat;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for płyta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="płyta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tytuł" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="artysta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cena" type="{http://moj.pl/xmlschemat}cena"/>
 *         &lt;element name="dataWydania" type="{http://moj.pl/xmlschemat}dataWydania"/>
 *         &lt;element name="liczbaSztuk" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *         &lt;element name="wydawcaPłyty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="wydawcaID" use="required" type="{http://moj.pl/xmlschemat}wydawcaID" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gatunek">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="nazwa" default="Inny">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="Pop"/>
 *                       &lt;enumeration value="Rock"/>
 *                       &lt;enumeration value="Country"/>
 *                       &lt;enumeration value="Jazz"/>
 *                       &lt;enumeration value="Disco"/>
 *                       &lt;enumeration value="Inny"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://moj.pl/xmlschemat}atrybutyPłyty"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "płyta", propOrder = {
    "tytuł",
    "artysta",
    "cena",
    "dataWydania",
    "liczbaSztuk",
    "wydawcaPłyty",
    "gatunek"
})
public class Płyta {

    @XmlElement(required = true)
    protected String tytuł;
    @XmlElement(required = true)
    protected String artysta;
    @XmlElement(required = true)
    protected Cena cena;
    @XmlElement(required = true)
    protected DataWydania dataWydania;
    @XmlElement(required = true)
    protected Object liczbaSztuk;
    @XmlElement(required = true)
    protected Płyta.WydawcaPłyty wydawcaPłyty;
    @XmlElement(required = true)
    protected Płyta.Gatunek gatunek;
    @XmlAttribute(name = "płytaID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String płytaID;
    @XmlAttribute(name = "polska")
    protected String polska;
    @XmlAttribute(name = "inniWykonawcyIDS")
    @XmlIDREF
    protected List<Object> inniWykonawcyIDS;

    /**
     * Gets the value of the tytuł property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTytuł() {
        return tytuł;
    }

    /**
     * Sets the value of the tytuł property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTytuł(String value) {
        this.tytuł = value;
    }

    /**
     * Gets the value of the artysta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtysta() {
        return artysta;
    }

    /**
     * Sets the value of the artysta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtysta(String value) {
        this.artysta = value;
    }

    /**
     * Gets the value of the cena property.
     * 
     * @return
     *     possible object is
     *     {@link Cena }
     *     
     */
    public Cena getCena() {
        return cena;
    }

    /**
     * Sets the value of the cena property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cena }
     *     
     */
    public void setCena(Cena value) {
        this.cena = value;
    }

    /**
     * Gets the value of the dataWydania property.
     * 
     * @return
     *     possible object is
     *     {@link DataWydania }
     *     
     */
    public DataWydania getDataWydania() {
        return dataWydania;
    }

    /**
     * Sets the value of the dataWydania property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataWydania }
     *     
     */
    public void setDataWydania(DataWydania value) {
        this.dataWydania = value;
    }

    /**
     * Gets the value of the liczbaSztuk property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLiczbaSztuk() {
        return liczbaSztuk;
    }

    /**
     * Sets the value of the liczbaSztuk property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLiczbaSztuk(Object value) {
        this.liczbaSztuk = value;
    }

    /**
     * Gets the value of the wydawcaPłyty property.
     * 
     * @return
     *     possible object is
     *     {@link Płyta.WydawcaPłyty }
     *     
     */
    public Płyta.WydawcaPłyty getWydawcaPłyty() {
        return wydawcaPłyty;
    }

    /**
     * Sets the value of the wydawcaPłyty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Płyta.WydawcaPłyty }
     *     
     */
    public void setWydawcaPłyty(Płyta.WydawcaPłyty value) {
        this.wydawcaPłyty = value;
    }

    /**
     * Gets the value of the gatunek property.
     * 
     * @return
     *     possible object is
     *     {@link Płyta.Gatunek }
     *     
     */
    public Płyta.Gatunek getGatunek() {
        return gatunek;
    }

    /**
     * Sets the value of the gatunek property.
     * 
     * @param value
     *     allowed object is
     *     {@link Płyta.Gatunek }
     *     
     */
    public void setGatunek(Płyta.Gatunek value) {
        this.gatunek = value;
    }

    /**
     * Gets the value of the płytaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPłytaID() {
        return płytaID;
    }

    /**
     * Sets the value of the płytaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPłytaID(String value) {
        this.płytaID = value;
    }

    /**
     * Gets the value of the polska property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolska() {
        return polska;
    }

    /**
     * Sets the value of the polska property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolska(String value) {
        this.polska = value;
    }

    /**
     * Gets the value of the inniWykonawcyIDS property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inniWykonawcyIDS property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInniWykonawcyIDS().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getInniWykonawcyIDS() {
        if (inniWykonawcyIDS == null) {
            inniWykonawcyIDS = new ArrayList<Object>();
        }
        return this.inniWykonawcyIDS;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="nazwa" default="Inny">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="Pop"/>
     *             &lt;enumeration value="Rock"/>
     *             &lt;enumeration value="Country"/>
     *             &lt;enumeration value="Jazz"/>
     *             &lt;enumeration value="Disco"/>
     *             &lt;enumeration value="Inny"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Gatunek {

        @XmlAttribute(name = "nazwa")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String nazwa;

        /**
         * Gets the value of the nazwa property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazwa() {
            if (nazwa == null) {
                return "Inny";
            } else {
                return nazwa;
            }
        }

        /**
         * Sets the value of the nazwa property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazwa(String value) {
            this.nazwa = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="wydawcaID" use="required" type="{http://moj.pl/xmlschemat}wydawcaID" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class WydawcaPłyty {

        @XmlAttribute(name = "wydawcaID", required = true)
        protected String wydawcaID;

        /**
         * Gets the value of the wydawcaID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWydawcaID() {
            return wydawcaID;
        }

        /**
         * Sets the value of the wydawcaID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWydawcaID(String value) {
            this.wydawcaID = value;
        }

    }

}
