//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 06:26:03 AM CET 
//


package pl.moj.xmlschemat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wydawca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wydawca">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nazwa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="państwo" type="{http://moj.pl/xmlschemat}nazwaWłasna"/>
 *         &lt;element name="dataZałożenia" type="{http://moj.pl/xmlschemat}dataZałożenia"/>
 *         &lt;choice>
 *           &lt;element name="telefon" type="{http://moj.pl/xmlschemat}numerTelefonu"/>
 *           &lt;element name="adresEmail" type="{http://moj.pl/xmlschemat}adresEmail"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="wydawcaID" use="required" type="{http://moj.pl/xmlschemat}wydawcaID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wydawca", propOrder = {
    "nazwa",
    "pa\u0144stwo",
    "dataZa\u0142o\u017cenia",
    "telefon",
    "adresEmail"
})
public class Wydawca {

    @XmlElement(required = true)
    protected String nazwa;
    @XmlElement(required = true)
    protected String państwo;
    @XmlElement(required = true)
    protected DataZałożenia dataZałożenia;
    protected String telefon;
    protected String adresEmail;
    @XmlAttribute(name = "wydawcaID", required = true)
    protected String wydawcaID;

    /**
     * Gets the value of the nazwa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwa() {
        return nazwa;
    }

    /**
     * Sets the value of the nazwa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwa(String value) {
        this.nazwa = value;
    }

    /**
     * Gets the value of the państwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaństwo() {
        return państwo;
    }

    /**
     * Sets the value of the państwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaństwo(String value) {
        this.państwo = value;
    }

    /**
     * Gets the value of the dataZałożenia property.
     * 
     * @return
     *     possible object is
     *     {@link DataZałożenia }
     *     
     */
    public DataZałożenia getDataZałożenia() {
        return dataZałożenia;
    }

    /**
     * Sets the value of the dataZałożenia property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataZałożenia }
     *     
     */
    public void setDataZałożenia(DataZałożenia value) {
        this.dataZałożenia = value;
    }

    /**
     * Gets the value of the telefon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelefon() {
        return telefon;
    }

    /**
     * Sets the value of the telefon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelefon(String value) {
        this.telefon = value;
    }

    /**
     * Gets the value of the adresEmail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresEmail() {
        return adresEmail;
    }

    /**
     * Sets the value of the adresEmail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresEmail(String value) {
        this.adresEmail = value;
    }

    /**
     * Gets the value of the wydawcaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWydawcaID() {
        return wydawcaID;
    }

    /**
     * Sets the value of the wydawcaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWydawcaID(String value) {
        this.wydawcaID = value;
    }

}
