//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.10 at 06:26:03 AM CET 
//


package pl.moj.xmlschemat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for wykonawca complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="wykonawca">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="imie" type="{http://moj.pl/xmlschemat}nazwaWłasna"/>
 *         &lt;element name="nazwisko" type="{http://moj.pl/xmlschemat}nazwaWłasna"/>
 *       &lt;/sequence>
 *       &lt;attribute name="wykonawcaID" use="required" type="{http://moj.pl/xmlschemat}wykonawcaID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "wykonawca", propOrder = {
    "imie",
    "nazwisko"
})
public class Wykonawca {

    @XmlElement(required = true)
    protected String imie;
    @XmlElement(required = true)
    protected String nazwisko;
    @XmlAttribute(name = "wykonawcaID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    protected String wykonawcaID;

    /**
     * Gets the value of the imie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImie() {
        return imie;
    }

    /**
     * Sets the value of the imie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImie(String value) {
        this.imie = value;
    }

    /**
     * Gets the value of the nazwisko property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazwisko() {
        return nazwisko;
    }

    /**
     * Sets the value of the nazwisko property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazwisko(String value) {
        this.nazwisko = value;
    }

    /**
     * Gets the value of the wykonawcaID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWykonawcaID() {
        return wykonawcaID;
    }

    /**
     * Sets the value of the wykonawcaID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWykonawcaID(String value) {
        this.wykonawcaID = value;
    }

}
